### ISSUE TITLE
Clean UP & Dockerization eos8a4x

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos8a4x#6]

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron,
I made the necessary changes and created a [PR](https://github.com/ersilia-os/eos8a4x/pull/7)

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron,
Sorry I'm bringing this up again. But the error that[ failed arm64](https://github.com/ersilia-os/eos8a4x/actions/runs/5483670748/jobs/9990262641#step:7:3198) build can easily be fixed. I hdn't changed the docker file as I didn't expect rdkit 2021.3.5 to be missing for aarch, but I see it has to be `2021.9.4` and above. 
```
#8 565.7 ERROR: Could not find a version that satisfies the requirement rdkit-pypi==2021.3.5.1 (from versions: 2021.9.4, 2021.9.5.1, 2022.3.1b1, 2022.3.1, 2022.3.1.1, 2022.3.2, 2022.3.2.1, 2022.3.3, 2022.3.4, 2022.3.5, 2022.9.1, 2022.9.2, 2022.9.3, 2022.9.4, 2022.9.5, 2023.3.1b1)
#8 565.7 ERROR: No matching distribution found for rdkit-pypi==2021.3.5
```
Also, I checked the [original repo](https://github.com/bp-kelley/descriptastorus/blob/master/requirements.txt) and they now recommend `rdkit-pypi>=2022.3.3 `,  these are avialable for aarch.  I hope it's okay to upgrade rdkit so that we can have both images.

I created a [PR](https://github.com/ersilia-os/eos8a4x/pull/8) for this change
